
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  # <<: *default
  # database: app_development
  # username: user
  # password: password
  # host: localhost
    url: <%= ENV["RENDER_DATABASE_URL"] %>

test:
  <<: *default
  database: app_test
  username: user
  password: password
  host: localhost

production:
  <<: *default
  url: <%= ENV["RENDER_DATABASE_URL"] %>
